### ISSUE TITLE
Dúvida ao trabalhar com Intent + Dialog

### ISSUE THREAD

**Issue by odirleiborgert** [glaucia86/hands-on-bots-node#1]
Olá Glaucia,

Existe alguma maneira de eu mesclar o dialogo com a intenção para que eu não precise ter o trecho de código redundante?

```
bot.dialog('whats-your-name', require('./dialogs/whats-your-name'))
intents.matches('whats-your-name', require('./dialogs/whats-your-name'))
```

**Comment by glaucia86** [comment]
Usando de maneira waterfall. Estarei explicando sobre isso nas aulas seguintes! :)
