### ISSUE TITLE
Utilizando o session.userData

### ISSUE THREAD

**Issue by odirleiborgert** [glaucia86/hands-on-bots-node#4]
Dúvida ref. a aula 11

Uma dúvida é se eu estiver atribuindo um dado, por exemplo:
session.userData.name = "Fulano"

Para eu conseguir resgatar esse dado em outro diálogo eu preciso chamar o método session.save() ou não precisa?

**Comment by glaucia86** [comment]
Conseguiu encontrar a solução?

**Comment by odirleiborgert** [comment]
olá @glaucia86 ,

O problema era outro, como estava rodando local com o nodemon ele sempre limpava a sessão quando salvava alguma alteração, por isso que pensei que a sessão se perdia quando fosse para outro dialogo, mas não tinha problema algum...
