### ISSUE TITLE
Prompts.confirm em inglês

### ISSUE THREAD

**Issue by goncasthiago** [glaucia86/hands-on-bots-node#6]
Olá Glaucia,
Antes de tudo parabéns pelo material!

Na aula 15 você mostra o uso do Prompts.confirm no meu caso, eu nao havia configurado o locale como pt-br e as opções vieram como yes | no.

Tem como forçar que as opções sejam em português sem usar o Prompts.choice e definir na mão?

Obrigado

**Comment by glaucia86** [comment]
@goncasthiago dê uma olhada nesse artigo. Acho que vai te interessar: https://blog.botframework.com/2017/05/24/using-local-reg-exp-recognizer-node/

E obrigada. Lembrando que esse curso está desatualizado devido a nova versão que foi lançada v.4 e houve breaking changes. Tou tentando arranjar tempo para concluir o curso da versão 3 para depois começar a versão 4. 

Abraços,
